shared-version = true
consolidate-commits = true

tag-name = "v{{version}}"
tag-prefix = ""

sign-commit = true
sign-tag = true

pre-release-hook = ["bash", "-c", "cd $(dirname $(cargo locate-project --workspace --message-format plain)) && git cliff -o CHANGELOG.md --tag 'v{{version}}' && git add CHANGELOG.md"]
pre-release-commit-message = "chore(release): v{{version}}"

publish = true
push = false
