[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
rustdoc-query = { path = ".." }
schemars08 = { package = "schemars", version = "=0.8.22" }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
typify = "0.7.0"
