// @generated by xtask; do not edit.
//! Internal MCP bindings derived from the canonical contract schema.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct ToolContract {
    pub(crate) name: &'static str,
    pub(crate) request: &'static str,
    pub(crate) outcome: &'static str,
    pub(crate) omitted_input_fields: &'static [&'static str],
}

pub(crate) const TOOL_CONTRACTS: &[ToolContract] = &[
    ToolContract {
        name: "crate_overview",
        request: "OverviewRequest",
        outcome: "OverviewOutcome",
        omitted_input_fields: &["output_format"],
    },
    ToolContract {
        name: "find_items",
        request: "FindRequest",
        outcome: "FindOutcome",
        omitted_input_fields: &["output_format"],
    },
    ToolContract {
        name: "get_item",
        request: "GetItemRequest",
        outcome: "GetItemOutcome",
        omitted_input_fields: &["output_format"],
    },
];

pub(crate) trait McpRequest {
    fn requested_output_format(
        &self,
    ) -> ::std::option::Option<crate::contract::generated::OutputFormat>;
    fn select_output_format(&mut self, format: crate::contract::generated::OutputFormat);
}

impl McpRequest for crate::contract::generated::OverviewRequest {
    fn requested_output_format(
        &self,
    ) -> ::std::option::Option<crate::contract::generated::OutputFormat> {
        self.output_format
    }

    fn select_output_format(&mut self, format: crate::contract::generated::OutputFormat) {
        self.output_format = ::std::option::Option::Some(format);
    }
}
impl McpRequest for crate::contract::generated::FindRequest {
    fn requested_output_format(
        &self,
    ) -> ::std::option::Option<crate::contract::generated::OutputFormat> {
        self.output_format
    }

    fn select_output_format(&mut self, format: crate::contract::generated::OutputFormat) {
        self.output_format = ::std::option::Option::Some(format);
    }
}
impl McpRequest for crate::contract::generated::GetItemRequest {
    fn requested_output_format(
        &self,
    ) -> ::std::option::Option<crate::contract::generated::OutputFormat> {
        self.output_format
    }

    fn select_output_format(&mut self, format: crate::contract::generated::OutputFormat) {
        self.output_format = ::std::option::Option::Some(format);
    }
}

pub(crate) trait McpOutcome {
    fn is_tool_error(&self) -> bool;
}

impl McpOutcome for crate::contract::generated::OverviewOutcome {
    fn is_tool_error(&self) -> bool {
        matches!(self, Self::ErrorOutcome(_))
    }
}
impl McpOutcome for crate::contract::generated::FindOutcome {
    fn is_tool_error(&self) -> bool {
        matches!(self, Self::ErrorOutcome(_))
    }
}
impl McpOutcome for crate::contract::generated::GetItemOutcome {
    fn is_tool_error(&self) -> bool {
        matches!(self, Self::ErrorOutcome(_))
    }
}
