//! Schema-derived Rust source generation.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use quote::ToTokens;
use schemars08::schema::RootSchema;
use serde_json::Value;
use syn::{Fields, Item, Type};
use typify::{TypeSpace, TypeSpaceSettings};

mod bounded;
mod defaults;
mod mcp;
#[cfg(test)]
mod tests;

const SCHEMA: &str = "schema/rustdoc-query.v2.schema.json";
const TYPES: &str = "schema/generated/rustdoc-query.v2.rs";
const DEFAULTS: &str = "schema/generated/rustdoc-query.v2.defaults.rs";
const STRICT_OPTION: &str = "schema/generated/rustdoc-query.v2.strict_option.rs";
const MCP: &str = "src/mcp/generated.rs";

#[derive(Clone, Copy, Debug)]
pub(crate) enum Mode {
    Generate,
    Check,
}

pub(crate) fn run(mode: Mode) -> Result<(), String> {
    let root = workspace_root()?;
    let schema = canonical_schema(&root)?;
    let types = generate_types(&schema)?;
    let defaults = generate_defaults(&schema)?;
    let strict_option = rustfmt(&strict_option_source())?;
    let mcp = rustfmt(&mcp::source(&schema)?)?;
    apply(mode, &root.join(TYPES), types)?;
    apply(mode, &root.join(DEFAULTS), defaults)?;
    apply(mode, &root.join(STRICT_OPTION), strict_option)?;
    apply(mode, &root.join(MCP), mcp)
}

fn workspace_root() -> Result<PathBuf, String> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| "xtask must live directly beneath the workspace root".to_owned())
}

fn canonical_schema(root: &Path) -> Result<Value, String> {
    let source = fs::read_to_string(root.join(SCHEMA)).map_err(|error| error.to_string())?;
    serde_json::from_str(&source).map_err(|error| error.to_string())
}

fn codegen_schema(schema: &Value) -> Result<Value, String> {
    let mut schema = schema.clone();
    let defaults = defaults::collect(&schema)?;
    for pointer in defaults.iter().map(|spec| &spec.pointer) {
        schema
            .pointer_mut(pointer)
            .and_then(Value::as_object_mut)
            .and_then(|object| object.remove("default"))
            .ok_or_else(|| format!("{pointer} must name a schema default"))?;
    }
    Ok(schema)
}

fn generate_types(schema: &Value) -> Result<String, String> {
    let bounded = bounded::collect(schema)?;
    let root: RootSchema =
        serde_json::from_value(codegen_schema(schema)?).map_err(|error| error.to_string())?;
    let mut settings = TypeSpaceSettings::default();
    settings.with_derive("rmcp::schemars::JsonSchema".to_owned());
    for spec in &bounded {
        settings.with_replacement(
            &spec.name,
            &spec.name,
            std::iter::empty::<typify::TypeSpaceImpl>(),
        );
    }
    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(root)
        .map_err(|error| error.to_string())?;
    let bounded_scalars = bounded::source(&bounded)?;
    let type_defaults = defaults::type_default_impls(schema)?;
    let source = rustfmt(&format!(
        "// @generated by xtask; do not edit.\n\
         #![allow(\n\
             clippy::derivable_impls,\n\
             clippy::enum_variant_names,\n\
             clippy::large_enum_variant\n\
         )]\n\n\
         {}\n\
         {bounded_scalars}\n\
         {type_defaults}",
        type_space.to_stream(),
    ))?;
    let source = add_strict_option_deserializers(schema, &source)?;
    let source = add_union_variant_docs(schema, &source)?;
    rustfmt(&source)
}

/// Adds docs for union variants whose schema descriptions Typify does not yet
/// emit. The canonical schema remains the single documentation source.
fn add_union_variant_docs(schema: &Value, source: &str) -> Result<String, String> {
    let definitions = schema
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| "schema must declare $defs".to_owned())?;
    let mut docs = BTreeMap::<String, BTreeMap<String, String>>::new();

    for (type_name, definition) in definitions {
        let Some(branches) = definition.get("oneOf").and_then(Value::as_array) else {
            continue;
        };
        let variants = branches
            .iter()
            .filter_map(|branch| {
                Some((
                    branch.get("title")?.as_str()?.to_owned(),
                    branch.get("description")?.as_str()?.to_owned(),
                ))
            })
            .collect::<BTreeMap<_, _>>();
        if !variants.is_empty() {
            docs.insert(type_name.clone(), variants);
        }
    }

    let mut file = syn::parse_file(source).map_err(|error| error.to_string())?;
    for item in &mut file.items {
        let Item::Enum(item_enum) = item else {
            continue;
        };
        let Some(variants) = docs.get(&item_enum.ident.to_string()) else {
            continue;
        };
        for variant in &mut item_enum.variants {
            let Some(description) = variants.get(&variant.ident.to_string()) else {
                continue;
            };
            variant.attrs.push(syn::parse_quote!(#[doc = #description]));
        }
    }

    Ok(file.into_token_stream().to_string())
}

fn add_strict_option_deserializers(schema: &Value, source: &str) -> Result<String, String> {
    let (optional_fields, optional_variant_fields) = schema_optional_fields(schema)?;
    let mut file = syn::parse_file(source).map_err(|error| error.to_string())?;

    for item in &mut file.items {
        match item {
            Item::Struct(item_struct) => {
                let Some(fields) = optional_fields.get(&item_struct.ident.to_string()) else {
                    continue;
                };
                let Fields::Named(named_fields) = &mut item_struct.fields else {
                    continue;
                };
                add_strict_option_attributes(&mut named_fields.named, fields)?;
            }
            Item::Enum(item_enum) => {
                let Some(variants) = optional_variant_fields.get(&item_enum.ident.to_string())
                else {
                    continue;
                };
                for variant in &mut item_enum.variants {
                    let Some(fields) = variants.get(&variant.ident.to_string()) else {
                        continue;
                    };
                    let Fields::Named(named_fields) = &mut variant.fields else {
                        continue;
                    };
                    add_strict_option_attributes(&mut named_fields.named, fields)?;
                }
            }
            _ => {}
        }
    }

    Ok(file.into_token_stream().to_string())
}

fn add_strict_option_attributes(
    fields: &mut syn::punctuated::Punctuated<syn::Field, syn::Token![,]>,
    optional_fields: &BTreeSet<String>,
) -> Result<(), String> {
    for field in fields {
        let field_name = serialized_field_name(field)?;
        if !optional_fields.contains(&field_name) || !is_option(&field.ty) {
            continue;
        }
        field.attrs.push(syn::parse_quote!(
            #[serde(deserialize_with = "super::strict_option::deserialize")]
        ));
    }
    Ok(())
}

type OptionalFields = BTreeMap<String, BTreeSet<String>>;
type OptionalVariantFields = BTreeMap<String, OptionalFields>;

fn schema_optional_fields(
    schema: &Value,
) -> Result<(OptionalFields, OptionalVariantFields), String> {
    let definitions = schema
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| "schema must declare $defs".to_owned())?;

    let mut optional_fields = OptionalFields::new();
    let mut optional_variant_fields = OptionalVariantFields::new();
    for (name, definition) in definitions {
        if let Some(fields) = optional_properties(definition) {
            optional_fields.insert(name.clone(), fields);
        }
        let variants = definition
            .get("oneOf")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(|branch| {
                Some((
                    branch.get("title")?.as_str()?.to_owned(),
                    optional_properties(branch)?,
                ))
            })
            .collect::<OptionalFields>();
        if !variants.is_empty() {
            optional_variant_fields.insert(name.clone(), variants);
        }
    }
    Ok((optional_fields, optional_variant_fields))
}

fn optional_properties(definition: &Value) -> Option<BTreeSet<String>> {
    let properties = definition.get("properties")?.as_object()?;
    let required = definition
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    Some(
        properties
            .keys()
            .filter(|property| !required.contains(property.as_str()))
            .cloned()
            .collect(),
    )
}

fn is_option(ty: &Type) -> bool {
    matches!(
        ty,
        Type::Path(path) if path.path.segments.last().is_some_and(|segment| segment.ident == "Option")
    )
}

fn serialized_field_name(field: &syn::Field) -> Result<String, String> {
    let mut name = field
        .ident
        .as_ref()
        .map(ToString::to_string)
        .ok_or_else(|| "schema-generated struct fields must be named".to_owned())?;
    for attribute in &field.attrs {
        if !attribute.path().is_ident("serde") {
            continue;
        }
        attribute
            .parse_nested_meta(|meta| {
                if !meta.path.is_ident("rename") {
                    if meta.input.peek(syn::Token![=]) {
                        let value = meta.value()?;
                        let _: syn::Expr = value.parse()?;
                    } else if meta.input.peek(syn::token::Paren) {
                        meta.parse_nested_meta(|nested| {
                            if nested.input.peek(syn::Token![=]) {
                                let value = nested.value()?;
                                let _: syn::Expr = value.parse()?;
                            }
                            Ok(())
                        })?;
                    }
                    return Ok(());
                }
                name = meta.value()?.parse::<syn::LitStr>()?.value();
                Ok(())
            })
            .map_err(|error| error.to_string())?;
    }
    Ok(name)
}

fn generate_defaults(schema: &Value) -> Result<String, String> {
    let source = defaults::source(schema)?;
    rustfmt(&source)
}

fn strict_option_source() -> String {
    "// @generated by xtask; do not edit.\n\
     //! Reject explicit JSON null for optional contract fields.\n\n\
     use std::marker::PhantomData;\n\n\
     use serde::{Deserialize, Deserializer};\n\n\
     pub(crate) fn deserialize<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>\n\
     where\n\
         D: Deserializer<'de>,\n\
         T: Deserialize<'de>,\n\
     {\n\
         deserializer.deserialize_option(RejectNull(PhantomData))\n\
     }\n\n\
     struct RejectNull<T>(PhantomData<T>);\n\n\
     impl<'de, T> serde::de::Visitor<'de> for RejectNull<T>\n\
     where\n\
         T: Deserialize<'de>,\n\
     {\n\
         type Value = Option<T>;\n\n\
         fn expecting(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n\
             formatter.write_str(\"a non-null value or an omitted field\")\n\
         }\n\n\
         fn visit_none<E>(self) -> Result<Self::Value, E>\n\
         where\n\
             E: serde::de::Error,\n\
         {\n\
             Err(E::custom(\"null is not allowed; omit the field instead\"))\n\
         }\n\n\
         fn visit_unit<E>(self) -> Result<Self::Value, E>\n\
         where\n\
             E: serde::de::Error,\n\
         {\n\
             self.visit_none()\n\
         }\n\n\
         fn visit_some<D>(self, deserializer: D) -> Result<Self::Value, D::Error>\n\
         where\n\
             D: Deserializer<'de>,\n\
         {\n\
             T::deserialize(deserializer).map(Some)\n\
         }\n\
     }\n"
    .to_owned()
}

fn rustfmt(source: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|error| error.to_string())?;
    child
        .stdin
        .as_mut()
        .ok_or_else(|| "rustfmt stdin is unavailable".to_owned())?
        .write_all(source.as_bytes())
        .map_err(|error| error.to_string())?;
    let output = child
        .wait_with_output()
        .map_err(|error| error.to_string())?;
    if !output.status.success() {
        return Err("rustfmt failed while formatting generated source".to_owned());
    }
    String::from_utf8(output.stdout).map_err(|error| error.to_string())
}

fn apply(mode: Mode, path: &Path, generated: String) -> Result<(), String> {
    match mode {
        Mode::Generate => fs::write(path, generated).map_err(|error| error.to_string()),
        Mode::Check => {
            let checked_in = fs::read_to_string(path).map_err(|error| error.to_string())?;
            if checked_in == generated {
                Ok(())
            } else {
                Err(format!(
                    "{} is stale; run just generate-schema",
                    path.display()
                ))
            }
        }
    }
}
