//! Schema-derived Rust source generation.

use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use schemars08::schema::RootSchema;
use serde_json::Value;
use typify::{TypeSpace, TypeSpaceSettings};

mod bounded;
mod defaults;
mod mcp;
#[cfg(test)]
mod tests;

const SCHEMA: &str = "schema/rustdoc-query.v1.schema.json";
const TYPES: &str = "schema/generated/rustdoc-query.v1.rs";
const DEFAULTS: &str = "schema/generated/rustdoc-query.v1.defaults.rs";
const STRICT_OPTION: &str = "schema/generated/rustdoc-query.v1.strict_option.rs";
const MCP: &str = "src/mcp/generated.rs";

#[derive(Clone, Copy, Debug)]
pub(crate) enum Mode {
    Generate,
    Check,
}

pub(crate) fn run(mode: Mode) -> Result<(), String> {
    let root = workspace_root()?;
    let schema = canonical_schema(&root)?;
    let types = generate_types(&schema)?;
    let defaults = generate_defaults(&schema)?;
    let strict_option = rustfmt(&strict_option_source())?;
    let mcp = rustfmt(&mcp::source(&schema)?)?;
    apply(mode, &root.join(TYPES), types)?;
    apply(mode, &root.join(DEFAULTS), defaults)?;
    apply(mode, &root.join(STRICT_OPTION), strict_option)?;
    apply(mode, &root.join(MCP), mcp)
}

fn workspace_root() -> Result<PathBuf, String> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| "xtask must live directly beneath the workspace root".to_owned())
}

fn canonical_schema(root: &Path) -> Result<Value, String> {
    let source = fs::read_to_string(root.join(SCHEMA)).map_err(|error| error.to_string())?;
    serde_json::from_str(&source).map_err(|error| error.to_string())
}

fn codegen_schema(schema: &Value) -> Result<Value, String> {
    let mut schema = schema.clone();
    let defaults = defaults::collect(&schema)?;
    for pointer in defaults.iter().map(|spec| &spec.pointer) {
        schema
            .pointer_mut(pointer)
            .and_then(Value::as_object_mut)
            .and_then(|object| object.remove("default"))
            .ok_or_else(|| format!("{pointer} must name a schema default"))?;
    }
    Ok(schema)
}

fn generate_types(schema: &Value) -> Result<String, String> {
    let bounded = bounded::collect(schema)?;
    let root: RootSchema =
        serde_json::from_value(codegen_schema(schema)?).map_err(|error| error.to_string())?;
    let mut settings = TypeSpaceSettings::default();
    settings.with_derive("rmcp::schemars::JsonSchema".to_owned());
    for spec in &bounded {
        settings.with_replacement(
            &spec.name,
            &spec.name,
            std::iter::empty::<typify::TypeSpaceImpl>(),
        );
    }
    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(root)
        .map_err(|error| error.to_string())?;
    let bounded_scalars = bounded::source(&bounded)?;
    let type_defaults = defaults::type_default_impls(schema)?;
    let source = rustfmt(&format!(
        "// @generated by xtask; do not edit.\n\
         #![allow(\n\
             clippy::derivable_impls,\n\
             clippy::enum_variant_names,\n\
             clippy::large_enum_variant\n\
         )]\n\n\
         {}\n\
         {bounded_scalars}\n\
         {type_defaults}",
        type_space.to_stream(),
    ))?;
    rustfmt(&add_strict_option_deserializers(&source))
}

fn add_strict_option_deserializers(source: &str) -> String {
    const OPTION_ATTRIBUTE: &str =
        "    #[serde(default, skip_serializing_if = \"::std::option::Option::is_none\")]";
    source.replace(
        OPTION_ATTRIBUTE,
        &format!(
            "{OPTION_ATTRIBUTE}\n    #[serde(deserialize_with = \"super::strict_option::deserialize\")]"
        ),
    )
}

fn generate_defaults(schema: &Value) -> Result<String, String> {
    let source = defaults::source(schema)?;
    rustfmt(&source)
}

fn strict_option_source() -> String {
    "// @generated by xtask; do not edit.\n\
     //! Reject explicit JSON null for optional contract fields.\n\n\
     use std::marker::PhantomData;\n\n\
     use serde::{Deserialize, Deserializer};\n\n\
     pub(crate) fn deserialize<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>\n\
     where\n\
         D: Deserializer<'de>,\n\
         T: Deserialize<'de>,\n\
     {\n\
         deserializer.deserialize_option(RejectNull(PhantomData))\n\
     }\n\n\
     struct RejectNull<T>(PhantomData<T>);\n\n\
     impl<'de, T> serde::de::Visitor<'de> for RejectNull<T>\n\
     where\n\
         T: Deserialize<'de>,\n\
     {\n\
         type Value = Option<T>;\n\n\
         fn expecting(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n\
             formatter.write_str(\"a non-null value or an omitted field\")\n\
         }\n\n\
         fn visit_none<E>(self) -> Result<Self::Value, E>\n\
         where\n\
             E: serde::de::Error,\n\
         {\n\
             Err(E::custom(\"null is not allowed; omit the field instead\"))\n\
         }\n\n\
         fn visit_unit<E>(self) -> Result<Self::Value, E>\n\
         where\n\
             E: serde::de::Error,\n\
         {\n\
             self.visit_none()\n\
         }\n\n\
         fn visit_some<D>(self, deserializer: D) -> Result<Self::Value, D::Error>\n\
         where\n\
             D: Deserializer<'de>,\n\
         {\n\
             T::deserialize(deserializer).map(Some)\n\
         }\n\
     }\n"
    .to_owned()
}

fn rustfmt(source: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|error| error.to_string())?;
    child
        .stdin
        .as_mut()
        .ok_or_else(|| "rustfmt stdin is unavailable".to_owned())?
        .write_all(source.as_bytes())
        .map_err(|error| error.to_string())?;
    let output = child
        .wait_with_output()
        .map_err(|error| error.to_string())?;
    if !output.status.success() {
        return Err("rustfmt failed while formatting generated source".to_owned());
    }
    String::from_utf8(output.stdout).map_err(|error| error.to_string())
}

fn apply(mode: Mode, path: &Path, generated: String) -> Result<(), String> {
    match mode {
        Mode::Generate => fs::write(path, generated).map_err(|error| error.to_string()),
        Mode::Check => {
            let checked_in = fs::read_to_string(path).map_err(|error| error.to_string())?;
            if checked_in == generated {
                Ok(())
            } else {
                Err(format!(
                    "{} is stale; run just generate-schema",
                    path.display()
                ))
            }
        }
    }
}
