//! Discovers optional request defaults and emits private service constants.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};

use serde_json::Value;

#[derive(Debug)]
pub(super) struct Spec {
    pub(super) pointer: String,
    symbol: String,
    value: Value,
    minimum: Option<u64>,
    maximum: Option<u64>,
}

pub(super) fn collect(schema: &Value) -> Result<Vec<Spec>, String> {
    let definitions = defs(schema)?;
    let mut specs = BTreeMap::new();
    for (request_name, request) in definitions {
        if !request_name.ends_with("Request") {
            continue;
        }
        let required = request
            .get("required")
            .and_then(Value::as_array)
            .ok_or_else(|| format!("{request_name} must declare required fields"))?
            .iter()
            .filter_map(Value::as_str)
            .collect::<BTreeSet<_>>();
        let properties = request
            .get("properties")
            .and_then(Value::as_object)
            .ok_or_else(|| format!("{request_name} must declare properties"))?;
        for (field_name, property) in properties {
            if required.contains(field_name.as_str()) {
                continue;
            }
            let (target, pointer, symbol) =
                resolved_default(schema, request_name, field_name, property)?;
            let Some(value) = target.get("default") else {
                continue;
            };
            specs.entry(pointer.clone()).or_insert_with(|| Spec {
                pointer,
                symbol,
                value: value.clone(),
                minimum: target.get("minimum").and_then(Value::as_u64),
                maximum: target.get("maximum").and_then(Value::as_u64),
            });
        }
    }
    Ok(specs.into_values().collect())
}

pub(super) fn source(schema: &Value) -> Result<String, String> {
    let mut declarations = String::new();
    for spec in collect(schema)? {
        if is_string_enum_default(schema, &spec) {
            continue;
        }
        declarations.push_str(&default_declaration(&spec)?);
    }
    Ok(format!(
        "// @generated by xtask; do not edit.\n\
         //! Private service defaults derived from optional request fields.\n\n\
         {declarations}"
    ))
}

fn is_string_enum_default(schema: &Value, spec: &Spec) -> bool {
    let Some(definition_name) = spec.pointer.strip_prefix("/$defs/") else {
        return false;
    };
    if definition_name.contains('/') {
        return false;
    }
    defs(schema)
        .ok()
        .and_then(|definitions| definitions.get(definition_name))
        .is_some_and(|definition| {
            definition.get("default").is_some_and(Value::is_string)
                && string_enum_values(definition).is_some()
        })
}

/// Emits `Default` impls for the enum request defaults `source` skips —
/// Typify requires these as unconditional type-level defaults, not constants.
pub(super) fn type_default_impls(schema: &Value) -> Result<String, String> {
    let definitions = defs(schema)?;
    let mut impls = String::new();

    for spec in collect(schema)? {
        let Some(definition_name) = spec.pointer.strip_prefix("/$defs/") else {
            continue;
        };
        if definition_name.contains('/') {
            continue;
        }
        let definition = definitions
            .get(definition_name)
            .ok_or_else(|| format!("{} must resolve", spec.pointer))?;
        let Some(default) = definition.get("default").and_then(Value::as_str) else {
            continue;
        };
        let Some(values) = string_enum_values(definition) else {
            continue;
        };
        if !values.contains(&default) {
            return Err(format!(
                "{} default must be one of its string enum values",
                spec.pointer
            ));
        }

        let type_name = rust_identifier(definition_name)?;
        let variant_name = rust_identifier(default)?;
        writeln!(
            impls,
            "impl ::std::default::Default for {type_name} {{\n    fn default() -> Self {{\n        Self::{variant_name}\n    }}\n}}\n"
        )
        .map_err(|_| "writing to String failed".to_owned())?;
    }

    Ok(impls)
}

/// Returns the allowed strings from either supported canonical enum shape.
///
/// A flat `enum` remains useful for simple validation, while `oneOf` with
/// singleton `const` branches additionally carries per-variant documentation.
fn string_enum_values(definition: &Value) -> Option<Vec<&str>> {
    if let Some(values) = definition.get("enum").and_then(Value::as_array) {
        return values.iter().map(Value::as_str).collect();
    }

    definition
        .get("oneOf")
        .and_then(Value::as_array)?
        .iter()
        .map(|branch| branch.get("const").and_then(Value::as_str))
        .collect()
}

fn resolved_default<'a>(
    schema: &'a Value,
    request_name: &str,
    field_name: &str,
    property: &'a Value,
) -> Result<(&'a Value, String, String), String> {
    let Some(reference) = property.get("$ref").and_then(Value::as_str) else {
        return Ok((
            property,
            format!("/$defs/{request_name}/properties/{field_name}"),
            symbol(&format!("{request_name}_{field_name}")),
        ));
    };
    let definition = reference
        .strip_prefix("#/$defs/")
        .ok_or_else(|| format!("{reference} must be a local definition reference"))?;
    let target = defs(schema)?
        .get(definition)
        .ok_or_else(|| format!("{reference} must resolve"))?;
    Ok((target, format!("/$defs/{definition}"), symbol(definition)))
}

fn default_declaration(spec: &Spec) -> Result<String, String> {
    match &spec.value {
        Value::Bool(value) => Ok(format!(
            "pub(crate) const {}: bool = {value};\n",
            spec.symbol
        )),
        Value::String(value) => Ok(format!(
            "pub(crate) const {}: &str = {};\n",
            spec.symbol,
            serde_json::to_string(value).map_err(|error| error.to_string())?
        )),
        Value::Number(value) => integer_declaration(spec, value.as_u64()),
        _ => Err(format!("{} has an unsupported default type", spec.pointer)),
    }
}

fn integer_declaration(spec: &Spec, value: Option<u64>) -> Result<String, String> {
    let value = value.ok_or_else(|| format!("{} must be an unsigned integer", spec.pointer))?;
    if spec
        .maximum
        .is_some_and(|maximum| u8::try_from(maximum).is_ok())
    {
        return Ok(format!("pub(crate) const {}: u8 = {value};\n", spec.symbol));
    }
    if spec
        .maximum
        .is_some_and(|maximum| u16::try_from(maximum).is_ok())
    {
        return Ok(format!(
            "pub(crate) const {}: u16 = {value};\n",
            spec.symbol
        ));
    }
    if spec
        .maximum
        .is_some_and(|maximum| u32::try_from(maximum).is_ok())
    {
        return Ok(format!(
            "pub(crate) const {}: u32 = {value};\n",
            spec.symbol
        ));
    }
    if spec.minimum.is_some_and(|minimum| minimum >= 1) {
        return Ok(format!(
            "pub(crate) const {}: ::std::num::NonZeroU64 = match ::std::num::NonZeroU64::new({value}) {{\n\
             Some(value) => value,\n\
             None => panic!(\"{} default must be non-zero\"),\n\
             }};\n",
            spec.symbol, spec.pointer
        ));
    }
    Ok(format!(
        "pub(crate) const {}: u64 = {value};\n",
        spec.symbol
    ))
}

fn defs(schema: &Value) -> Result<&serde_json::Map<String, Value>, String> {
    schema
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| "schema must declare $defs".to_owned())
}

fn symbol(name: &str) -> String {
    let mut output = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() && index > 0 {
            output.push('_');
        }
        output.extend(character.to_uppercase());
    }
    output
}

fn rust_identifier(value: &str) -> Result<String, String> {
    let mut identifier = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if capitalize {
                identifier.extend(character.to_uppercase());
                capitalize = false;
            } else {
                identifier.push(character);
            }
        } else {
            capitalize = true;
        }
    }
    if identifier.is_empty()
        || !identifier.starts_with(|character: char| character.is_ascii_alphabetic())
    {
        return Err(format!("{value:?} cannot become a Rust enum variant"));
    }
    if !typify::accept_as_ident(&identifier) {
        identifier.push('_');
    }
    Ok(identifier)
}
