//! Generates internal MCP bindings from the canonical contract schema.

use std::{collections::BTreeSet, fmt::Write};

use serde_json::Value;

pub(super) fn source(schema: &Value) -> Result<String, String> {
    let definitions = defs(schema)?;
    let tools = schema
        .get("x-mcp-tools")
        .and_then(Value::as_array)
        .ok_or_else(|| "schema must declare x-mcp-tools".to_owned())?;
    if tools.is_empty() {
        return Err("x-mcp-tools must not be empty".to_owned());
    }

    let mut names = BTreeSet::new();
    let mut contracts = String::new();
    let mut request_impls = String::new();
    let mut outcome_impls = String::new();

    for tool in tools {
        let object = tool
            .as_object()
            .ok_or_else(|| "x-mcp-tools entries must be objects".to_owned())?;
        let name = string(object, "name")?;
        let request = string(object, "request")?;
        let outcome = string(object, "outcome")?;
        if !names.insert(name) {
            return Err(format!("x-mcp-tools repeats tool name {name}"));
        }
        validate_request(definitions, request)?;
        validate_outcome(definitions, outcome)?;
        writeln!(
            contracts,
            "    ToolContract {{ name: {name:?}, request: {request:?}, outcome: {outcome:?}, omitted_input_fields: &[\"output_format\"] }},"
        )
        .map_err(|_| "writing to String failed".to_owned())?;
        writeln!(
            request_impls,
            "impl McpRequest for crate::contract::generated::{request} {{\n    fn requested_output_format(&self) -> ::std::option::Option<crate::contract::generated::OutputFormat> {{\n        self.output_format\n    }}\n\n    fn select_output_format(&mut self, format: crate::contract::generated::OutputFormat) {{\n        self.output_format = ::std::option::Option::Some(format);\n    }}\n}}"
        )
        .map_err(|_| "writing to String failed".to_owned())?;
        writeln!(
            outcome_impls,
            "impl McpOutcome for crate::contract::generated::{outcome} {{\n    fn is_tool_error(&self) -> bool {{\n        matches!(self, Self::ErrorOutcome(_))\n    }}\n}}"
        )
        .map_err(|_| "writing to String failed".to_owned())?;
    }

    Ok(format!(
        "// @generated by xtask; do not edit.\n\
         //! Internal MCP bindings derived from the canonical contract schema.\n\n\
         #[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
         pub(crate) struct ToolContract {{\n\
             pub(crate) name: &'static str,\n\
             pub(crate) request: &'static str,\n\
             pub(crate) outcome: &'static str,\n\
             pub(crate) omitted_input_fields: &'static [&'static str],\n\
         }}\n\n\
         pub(crate) const TOOL_CONTRACTS: &[ToolContract] = &[\n{contracts}];\n\n\
         pub(crate) trait McpRequest {{\n\
             fn requested_output_format(&self) -> ::std::option::Option<crate::contract::generated::OutputFormat>;\n\
             fn select_output_format(&mut self, format: crate::contract::generated::OutputFormat);\n\
         }}\n\n\
         {request_impls}\n\
         pub(crate) trait McpOutcome {{\n\
             fn is_tool_error(&self) -> bool;\n\
         }}\n\n\
         {outcome_impls}"
    ))
}

fn defs(schema: &Value) -> Result<&serde_json::Map<String, Value>, String> {
    schema
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| "schema must declare $defs".to_owned())
}

fn string<'a>(object: &'a serde_json::Map<String, Value>, key: &str) -> Result<&'a str, String> {
    object
        .get(key)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("x-mcp-tools entry must declare string {key}"))
}

fn validate_request(
    definitions: &serde_json::Map<String, Value>,
    name: &str,
) -> Result<(), String> {
    let properties = definitions
        .get(name)
        .and_then(|value| value.get("properties"))
        .and_then(Value::as_object)
        .ok_or_else(|| format!("MCP request {name} must name an object definition"))?;
    let output_format = properties
        .get("output_format")
        .and_then(Value::as_object)
        .and_then(|value| value.get("$ref"))
        .and_then(Value::as_str);
    if output_format != Some("#/$defs/OutputFormat") {
        return Err(format!(
            "MCP request {name} must expose optional output_format"
        ));
    }
    Ok(())
}

fn validate_outcome(
    definitions: &serde_json::Map<String, Value>,
    name: &str,
) -> Result<(), String> {
    let branches = definitions
        .get(name)
        .and_then(|value| value.get("oneOf"))
        .and_then(Value::as_array)
        .ok_or_else(|| format!("MCP outcome {name} must declare oneOf"))?;
    if !branches
        .iter()
        .any(|branch| branch.get("$ref").and_then(Value::as_str) == Some("#/$defs/ErrorOutcome"))
    {
        return Err(format!("MCP outcome {name} must include ErrorOutcome"));
    }
    Ok(())
}
